"""Phase 1 — EDA & data-quality report for the CHARGED dataset.

Runs over all 6 cities and produces:
  - a data-quality summary (stdout + _output/eda_summary.md)
  - figures in _output/figures/

Usage:  python scripts/eda.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # non-interactive backend (no display)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.load import CITIES, city_total, load_sites, load_volume  # noqa: E402

OUT = ROOT / "_output"
FIG = OUT / "figures"
FIG.mkdir(parents=True, exist_ok=True)


def quality_row(city: str) -> dict:
    vol = load_volume(city)
    idx = pd.DatetimeIndex(vol.index)
    n_hours_expected = len(idx)
    # full hourly range from min to max
    full_range = pd.date_range(idx.min(), idx.max(), freq="h")
    n_missing = len(full_range.difference(idx))
    n_dup = idx.duplicated().sum()

    # all-zero sites (zero total volume over the whole period)
    n_all_zero = int((vol.sum(axis=0) == 0).sum())

    demand = vol.sum(axis=1)
    return {
        "city": city,
        "rows(hours)": vol.shape[0],
        "sites": vol.shape[1],
        "all_zero_sites": n_all_zero,
        "nan_cells": int(vol.isna().sum().sum()),
        "missing_hours": int(n_missing),
        "dup_index": int(n_dup),
        "start": idx.min().strftime("%Y-%m-%d"),
        "end": idx.max().strftime("%Y-%m-%d"),
        "demand_mean_kwh": demand.mean(),
        "demand_std_kwh": demand.std(),
        "demand_max_kwh": demand.max(),
        "zero_demand_pct": float((demand == 0).mean() * 100),
    }


def main() -> None:
    rows = [quality_row(c) for c in CITIES]
    summary = pd.DataFrame(rows).set_index("city")

    # --- console + markdown report ---
    with pd.option_context("display.width", 200, "display.float_format", "{:.2f}".format):
        print(summary)

    md_lines = [
        "# EDA — Data Quality Summary",
        "",
        "```",
        summary.to_string(),
        "```",
        "",
        "Generated by `scripts/eda.py`.",
    ]
    (OUT / "eda_summary.md").write_text("\n".join(md_lines), encoding="utf-8")

    # --- figures ---
    plot_time_series()
    plot_daily_cycle()
    plot_weekly_cycle()
    print(f"\nFigures saved to {FIG}")


def plot_time_series() -> None:
    fig, axes = plt.subplots(3, 2, figsize=(14, 10), sharex=True)
    for ax, city in zip(axes.flat, CITIES):
        demand = city_total(city)
        ax.plot(demand.index, demand.values, lw=0.6, color="#1f77b4")
        ax.set_title(city)
        ax.set_ylabel("kWh")
    fig.suptitle("City-level hourly charging demand (Apr–Sep 2023)", y=0.995)
    fig.tight_layout()
    fig.savefig(FIG / "time_series.png", dpi=110)
    plt.close(fig)


def plot_daily_cycle() -> None:
    fig, ax = plt.subplots(figsize=(10, 5))
    for city in CITIES:
        d = city_total(city)
        # normalize by mean so cities of different scale are comparable
        norm = d / d.mean()
        by_hour = norm.groupby(d.index.hour).mean()
        ax.plot(by_hour.index, by_hour.values, marker="o", ms=3, label=city)
    ax.axhline(1.0, color="gray", ls="--", lw=0.8)
    ax.set_xlabel("Hour of day")
    ax.set_ylabel("Demand / mean demand")
    ax.set_title("Average daily cycle (normalized by city mean)")
    ax.set_xticks(range(0, 24, 2))
    ax.legend(ncol=3)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIG / "daily_cycle.png", dpi=110)
    plt.close(fig)


def plot_weekly_cycle() -> None:
    fig, ax = plt.subplots(figsize=(10, 5))
    for city in CITIES:
        d = city_total(city)
        norm = d / d.mean()
        by_dow = norm.groupby(d.index.dayofweek).mean()
        ax.plot(by_dow.index, by_dow.values, marker="o", ms=3, label=city)
    ax.axhline(1.0, color="gray", ls="--", lw=0.8)
    ax.set_xlabel("Day of week (0=Mon)")
    ax.set_ylabel("Demand / mean demand")
    ax.set_title("Average weekly cycle (normalized by city mean)")
    ax.set_xticks(range(7))
    ax.set_xticklabels(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
    ax.legend(ncol=3)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIG / "weekly_cycle.png", dpi=110)
    plt.close(fig)


if __name__ == "__main__":
    main()
